#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/
#
# Configuration
font_family                 JetBrainsMono Nerd Font
font_size                   12
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
remember_window_size        no
initial_window_width        950
initial_window_height       500
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        10
hide_window_decorations     yes
background_opacity          0.7
dynamic_background_opacity  yes
confirm_os_window_close     0
selection_foreground        none
selection_background        none

# Animated cursor follows text
#include $HOME/.config/ml4w/settings/kitty-cursor-trail.conf

# Include matugen colors
allow_remote_control yes
include colors.conf

# Include Custom Configuration
# Create the file custom.conf in ~/.config/kitty to overwrite the default configuration
#include ./custom.conf

#foreground   #c2dce4
##background   #131219
#background   #171819
#cursor       #c2dce4
#
#color0       #131219
#color8       #879a9f
#color1       #8B78AF
#color9       #8B78AF
#color2       #6F93CC
#color10      #6F93CC
#color3       #73B1C3
#color11      #73B1C3
#color4       #7DB8CF
#color12      #7DB8CF
#color5       #8E93BA
#color13      #8E93BA
#color6       #84A7C7
#color14      #84A7C7
#color7       #c2dce4
#color15      #c2dce4
