save-watch-history
save-position-on-quit
sub-ass-override=force
embeddedfonts=no
sub-ass-style-overrides='Fontname=Noto Sans, Fontsize=24,BorderStyle=1,Outline=1,Shadow=0'
sub-font='Noto Sans'
sub-font-size=50
sub-color='#FFFFFFFF'
sub-border-color='#FF000000'
sub-border-size=2
sub-shadow-offset=2
sub-shadow-color='#33000000'
ytdl-format=bestvideo[height<=?1080][fps<=?60]+bestaudio/best
script-opts=ytdl_hook-ytdl_path=yt-dlp
cache-pause=yes
