# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = tile, title:^(Microsoft-edge)$
windowrule = tile, title:^(Brave-browser)$
windowrule = tile, class:^(Chromium)$
windowrule = float, title:^(pavucontrol)$
windowrule = float, title:^(blueman-manager)$
windowrule = float, title:^(nm-connection-editor)$
windowrule = float, title:^(qalculate-gtk)$
#windowrule = xray, class:^(chromium)$

#windowrule = xray 0, class:^(kitty)$

#windowrule = float, title:^(Waydroid)$
# Browser Picture in Picture
windowrule = float, title:^(Picture in picture)$
windowrule = keepaspectratio, title:^(Picture in picture)$
windowrule = pin, title:^(Picture in picture)$
windowrule = move 79% 2%, title:^(Picture in picture)$

#windowrule = keepaspectratio, class:^(mpv)$
windowrule = float, title:^(Screenshot)$
# idleinhibit
windowrule = idleinhibit fullscreen,class:([window]) # Available modes: none, always, focus, fullscreen
windowrule = workspace 2 silent,class:^(blueman-manager)$

